# Generated by Django 6.1 on 2026-08-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-transaction_date', '-created_at'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AddField(
            model_name='batch',
            name='payment_status',
            field=models.CharField(choices=[('NO_PAYMENT', 'No Payment'), ('PARTIAL_PAYMENT', 'Partial Payment'), ('FULL_PAYMENT', 'Full Payment')], default='NO_PAYMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_code',
            field=models.CharField(blank=True, help_text='Auto-generated if left empty (e.g. BUY-20260810-001)', max_length=50, unique=True),
        ),
    ]
