# Generated by Django 6.1 on 2026-08-10 13:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_batch_options_batch_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='total_batch_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
