# Generated by Django 6.1 on 2026-08-12 16:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_batch_total_batch_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='dry_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight after drying (~3 days). Leave blank if not dried yet.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='total_due_or_billed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='total_paid_or_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
