# Generated by Django 6.1 on 2026-08-12 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_batch_dry_weight_alter_ledger_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='account.batch')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='account.transaction')),
            ],
            options={
                'ordering': ['-allocated_at'],
                'constraints': [models.UniqueConstraint(fields=('transaction', 'batch'), name='unique_allocation_per_batch_txn')],
            },
        ),
    ]
