# Generated by Django 6.1 on 2026-08-14 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_paymentallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Leave empty for general overhead expenses', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='account.batch'),
        ),
    ]
