# Generated by Django 6.1 on 2026-08-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_expense_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Super Admin'), ('MANAGER', 'Manager'), ('STAFF', 'Staff / Operations'), ('VENDOR', 'Vendor / Supplier'), ('CLIENT', 'Client / Buyer')], default='STAFF', max_length=10),
        ),
    ]
