# Generated by Django 6.1 on 2026-08-16 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff/Manager who registered this batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff/Manager who recorded this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff/Manager who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
