# Generated by Django 6.1 on 2026-08-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_batch_created_by_expense_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Super Admin'), ('MANAGER', 'Manager'), ('STAFF', 'Staff / Operations'), ('VENDOR', 'Vendor / Supplier'), ('CLIENT', 'Client / Buyer')], default='ADMIN', max_length=10),
        ),
    ]
