# Generated by Django 6.1 on 2026-08-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_code',
            field=models.CharField(blank=True, default='', help_text='Bank Ref, Cheque Number, or Receipt Code', max_length=100),
        ),
    ]
