# Generated by Django 6.1 on 2026-09-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_transaction_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Super Admin'), ('MANAGER', 'Manager'), ('STAFF', 'Staff / Operations'), ('EATERY_MANAGER', 'Eatery-Manager'), ('VENDOR', 'Vendor / Supplier'), ('CLIENT', 'Client / Buyer')], default='ADMIN', max_length=20),
        ),
    ]
