# Generated by Django 6.1 on 2026-09-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Super Admin'), ('MANAGER', 'Manager'), ('STAFF', 'Staff / Operations'), ('EATERY_MANAGER', 'Eatery-Manager'), ('VENDOR', 'Vendor / Supplier'), ('CLIENT', 'Client / Buyer'), ('SUPERMARKET_MANAGER', 'Supermarket Manager')], default='ADMIN', max_length=30),
        ),
    ]
