# Generated by Django 6.1 on 2026-09-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0002_categoryattribute_productattribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermarketorderitem',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text='Whether tracked inventory was deducted when this order item was created.'),
        ),
    ]
